### ISSUE TITLE
OpenAPI support

### ISSUE THREAD

**Issue by kettanaito** [mswjs/source#10]
## What

We should support OpenAPI (Swagger) specification files as a source for handlers.

## How

We do have an initial implementation for this in `fromOpenApi`. At the moment, we use the response examples as mocked responses but it's not sufficient. 

### Generating values by types

We can use libraries like `faker` to generate random values for responses based on their structure. 

### Public API

I'd start from the runtime handler generation given a spec JSON:

```js
import { fromOpenApi } from '@mswjs/source'
import spec from './my.spec.json'

const handlers = fromOpenApi(spec)
```

## References

- [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)

## Roadmap

- [x] Add basic OpenAPI support (#11)
- [x] Add Petstore integration test #12 
- [x] Look into multiple response content types (do those mean _request_ `Accept` type?)
